/* ─── Design Tokens ──────────────────────────────────────────── */
export const tokens = {
  colors: {
    primary: 'var(--color-primary)',
    secondary: 'var(--color-secondary)',
    accent: 'var(--color-accent)',
    success: 'var(--color-success)',
    error: 'var(--color-error)',
    warning: 'var(--color-warning)',
    background: 'var(--color-background)',
    surface: 'var(--color-surface)',
    border: 'var(--color-border)',
    white: 'var(--color-white)',
    glass: 'rgba(255, 255, 255, 0.7)',
  },
  radius: { sm: '8px', md: '12px', lg: '16px', xl: '24px', full: '9999px' },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
  },
};

/* ─── Shared Styles ─────────────────────────────────────────── */
export const styles = {
  app: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: 'var(--color-background)',
    color: 'var(--color-primary)',
    fontFamily: '"Funnel Display", sans-serif',
    WebkitFontSmoothing: 'antialiased',
  },
  sidebar: {
    width: '280px',
    minWidth: '280px',
    backgroundColor: 'var(--color-sidebar-bg)',
    display: 'flex',
    flexDirection: 'column',
    padding: '40px 0',
    borderRight: '1px solid var(--color-border)',
    position: 'relative',
    zIndex: 10,
    transition: 'background-color 0.3s ease',
  },
  logo: {
    fontSize: '22px',
    fontWeight: '800',
    padding: '0 32px',
    marginBottom: '48px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    color: 'var(--color-primary)',
    letterSpacing: '-0.5px',
  },
  menuItem: (active) => ({
    margin: '4px 20px',
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
    borderRadius: '12px',
    backgroundColor: active ? 'var(--color-hover)' : 'transparent',
    color: active ? 'var(--color-accent)' : 'var(--color-secondary)',
    fontSize: '14px',
    fontWeight: active ? '600' : '500',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
  }),
  main: {
    flex: 1,
    padding: '48px 64px',
    overflowY: 'auto',
    backgroundColor: 'var(--color-background)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '48px',
  },
  topbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '32px',
    borderBottom: '1px solid var(--color-border)',
    marginBottom: '40px',
    backgroundColor: 'var(--color-topbar-bg)',
  },
  greeting: {
    fontSize: '28px',
    fontWeight: '800',
    color: 'var(--color-primary)',
    letterSpacing: '-0.02em',
  },
  card: {
    backgroundColor: 'var(--color-card-bg)',
    border: '1px solid var(--color-border)',
    padding: '32px',
    borderRadius: '16px',
    boxShadow: 'var(--shadow-sm)',
    transition: 'box-shadow 0.3s ease, background-color 0.3s ease',
  },
  button: {
    primary: {
      backgroundColor: 'var(--color-accent)',
      color: '#FFFFFF',
      border: 'none',
      padding: '12px 24px',
      borderRadius: '12px',
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '8px',
      boxShadow: '0 4px 6px -1px rgba(13, 148, 136, 0.2)',
    },
    outline: {
      backgroundColor: 'var(--color-white)',
      color: 'var(--color-primary)',
      border: '1px solid var(--color-border)',
      padding: '12px 24px',
      borderRadius: '12px',
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '8px',
    },
    ghost: {
      background: 'none',
      border: 'none',
      padding: '8px 12px',
      borderRadius: '8px',
      fontWeight: '600',
      fontSize: '13px',
      cursor: 'pointer',
      color: 'var(--color-secondary)',
      transition: 'all 0.2s ease',
    },
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid var(--color-border)',
    borderRadius: '12px',
    fontSize: '14px',
    outline: 'none',
    fontFamily: 'inherit',
    transition: 'all 0.2s ease',
    backgroundColor: 'var(--color-input-bg)',
    color: 'var(--color-primary)',
  },
  badge: (type) => ({
    padding: '6px 12px',
    borderRadius: '9999px',
    fontSize: '12px',
    fontWeight: '600',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: type === 'primary' ? 'rgba(13,148,136,0.1)' : 'var(--color-hover)',
    color: type === 'primary' ? 'var(--color-accent)' : 'var(--color-secondary)',
    border: `1px solid ${type === 'primary' ? 'rgba(13,148,136,0.2)' : 'var(--color-border)'}`,
  }),
  th: {
    textAlign: 'left',
    padding: '20px 16px',
    fontSize: '12px',
    fontWeight: '700',
    textTransform: 'uppercase',
    color: 'var(--color-secondary)',
    borderBottom: '1px solid var(--color-border)',
    letterSpacing: '0.05em',
    backgroundColor: 'var(--color-table-header)',
  },
  td: {
    padding: '20px 16px',
    fontSize: '14px',
    borderBottom: '1px solid var(--color-border)',
    color: 'var(--color-primary)',
  },
  modal: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(241, 245, 249, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    backdropFilter: 'blur(4px)',
    padding: '24px',
    animation: 'fadeIn 0.3s ease-out',
  },
};
