export const tokens = {
  colors: {
    primary: '#1A1A1A',
    secondary: '#4A4A4A',
    success: '#10B981',
    error: '#EF4444',
    warning: '#F59E0B',
    background: '#FAFAFA',
    surface: '#FFFFFF',
    border: '#E5E7EB',
    text: '#111827',
    textMuted: '#6B7280',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    full: '9999px',
  },
  shadow: {
    sm: '0 1px 2px rgba(0,0,0,0.05)',
    md: '0 4px 6px -1px rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)',
    lg: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)',
    heavy: '0 20px 25px -5px rgba(0,0,0,0.1), 0 10px 10px -5px rgba(0,0,0,0.04)',
  }
};

export const styles = {
  app: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: tokens.colors.background,
    color: tokens.colors.text,
    fontFamily: '"Inter", sans-serif',
  },
  sidebar: {
    width: '260px',
    backgroundColor: '#FFFFFF',
    color: '#000000',
    display: 'flex',
    flexDirection: 'column',
    padding: '32px 0',
    borderRight: `1px solid ${tokens.colors.border}`,
  },
  logo: {
    fontSize: '20px',
    fontWeight: '800',
    padding: '0 32px',
    marginBottom: '48px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    letterSpacing: '-0.5px',
    color: tokens.colors.primary,
  },
  menuItem: (active) => ({
    margin: '4px 16px',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
    borderRadius: tokens.radius.md,
    backgroundColor: active ? '#F3F4F6' : 'transparent',
    color: active ? tokens.colors.primary : tokens.colors.textMuted,
    fontSize: '14px',
    fontWeight: active ? '600' : '500',
    transition: 'all 0.2s ease',
  }),
  main: {
    flex: 1,
    padding: '40px',
    overflowY: 'auto',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '40px',
  },
  greeting: {
    fontSize: '24px',
    fontWeight: '700',
    color: tokens.colors.primary,
    marginBottom: '4px',
  },
  card: {
    backgroundColor: tokens.colors.surface,
    border: `1px solid ${tokens.colors.border}`,
    padding: '24px',
    borderRadius: tokens.radius.lg,
    boxShadow: tokens.shadow.sm,
    marginBottom: '24px',
  },
  button: {
    primary: {
      backgroundColor: tokens.colors.primary,
      color: '#FFFFFF',
      border: 'none',
      padding: '10px 20px',
      borderRadius: tokens.radius.md,
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    outline: {
      backgroundColor: '#FFFFFF',
      color: tokens.colors.primary,
      border: `1px solid ${tokens.colors.border}`,
      padding: '10px 20px',
      borderRadius: tokens.radius.md,
      fontWeight: '600',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    border: `1px solid ${tokens.colors.border}`,
    borderRadius: tokens.radius.md,
    fontSize: '14px',
    outline: 'none',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s ease',
    backgroundColor: '#FFFFFF',
  },
  badge: (type) => ({
    padding: '4px 10px',
    borderRadius: tokens.radius.full,
    fontSize: '11px',
    fontWeight: '600',
    display: 'inline-block',
    backgroundColor: type === 'primary' ? '#F3F4F6' : '#FFFFFF',
    color: type === 'primary' ? tokens.colors.primary : tokens.colors.textMuted,
    border: `1px solid ${tokens.colors.border}`,
  }),
  th: {
    textAlign: 'left',
    padding: '16px 12px',
    fontSize: '12px',
    fontWeight: '600',
    textTransform: 'uppercase',
    color: tokens.colors.textMuted,
    borderBottom: `1px solid ${tokens.colors.border}`,
    letterSpacing: '0.05em',
  },
  td: {
    padding: '16px 12px',
    fontSize: '14px',
    borderBottom: `1px solid ${tokens.colors.border}`,
    color: tokens.colors.text,
  },
};
